# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'JEAbout.ui'
##
## Created by: Qt User Interface Compiler version 5.15.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import *
from PySide2.QtGui import *
from PySide2.QtWidgets import *


class Ui_JEAboutDialog(object):
    def setupUi(self, JEAboutDialog):
        if not JEAboutDialog.objectName():
            JEAboutDialog.setObjectName(u"JEAboutDialog")
        JEAboutDialog.resize(450, 400)
        self.scrollArea = QScrollArea(JEAboutDialog)
        self.scrollArea.setObjectName(u"scrollArea")
        self.scrollArea.setGeometry(QRect(0, 0, 450, 400))
        self.scrollArea.setFrameShape(QFrame.NoFrame)
        self.scrollArea.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOn)
        self.scrollArea.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.scrollArea.setWidgetResizable(False)
        self.scrollAreaWidgetContents = QWidget()
        self.scrollAreaWidgetContents.setObjectName(u"scrollAreaWidgetContents")
        self.scrollAreaWidgetContents.setGeometry(QRect(0, 0, 440, 3760))
        self.aboutText = QLabel(self.scrollAreaWidgetContents)
        self.aboutText.setObjectName(u"aboutText")
        self.aboutText.setGeometry(QRect(10, 10, 420, 3760))
        self.aboutText.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignTop)
        self.aboutText.setWordWrap(True)
        self.aboutText.setOpenExternalLinks(True)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)

        self.retranslateUi(JEAboutDialog)

        QMetaObject.connectSlotsByName(JEAboutDialog)
    # setupUi

    def retranslateUi(self, JEAboutDialog):
        JEAboutDialog.setWindowTitle(QCoreApplication.translate("JEAboutDialog", u"About", None))
        self.aboutText.setText(QCoreApplication.translate("JEAboutDialog", u"<html><head/><body><p align=\"center\"><a href=\"https://github.com/N1GHT-MAR3/JuicedEditor\"><span style=\" font-weight:696; text-decoration: underline; color:#0000ff;\">Juiced Editor</span></a><span style=\" font-style:italic;\"> (version 1.1, 2023-03-13)<br/>by </span>N1GHTMAR3</p><p align=\"center\">Courtesy of the <a href=\"https://discord.gg/pu2jdxR\"><span style=\" text-decoration: underline; color:#0000ff;\">Juiced Modding Discord<br/></span></a>(if you need any help, come ask here!)</p><p align=\"center\"><span style=\" font-weight:696; text-decoration: underline;\">Special thanks</span><span style=\" text-decoration: underline;\"><br/></span><span style=\" font-weight:696;\">Bomb Bloke</span>: for unswizzling console textures with your DDT converter<span style=\" text-decoration: underline;\"><br/></span><span style=\" font-weight:696;\">Ekey</span>: for opening the floodgates with your <a href=\"https://github.com/Ekey/JCED.DAT.Tool/\"><span style=\" text-decoration: underline; color:#0000ff;\">unpa"
                        "cker</span></a><br/><span style=\" font-weight:696;\">GrimMaple</span>: for making the game playable with <a href=\"https://github.com/GrimMaple/JuicedFixes\"><span style=\" text-decoration: underline; color:#0000ff;\">JuicedFixes</span></a><br/><span style=\" font-weight:696;\">mariokart64n</span>: for JATool, your 3ds Max knowledge, and everything else<br/><span style=\" font-weight:696;\">Martin_SW</span>: for laying the groundwork of the modding scene<br/>The <span style=\" font-weight:696;\">OpenSpy</span> team: for <a href=\"http://beta.openspy.net/en/\"><span style=\" text-decoration: underline; color:#0000ff;\">making online play possible</span></a><br/><span style=\" font-weight:696;\">RedCarDriver</span>: for your gameplay overhauls and overall knowledge<br/><span style=\" font-weight:696;\">SxnnyB</span>: for your overarching knowledge, research, and consultation<br/><span style=\" font-weight:696;\">4ernobill, Eagle, LotusEliseBoy, Quadra, TFP, umi, ZA-7:</span><br/>for all your contributions to th"
                        "e scene</p><p align=\"center\">...and everyone else that's helped keep this game alive!</p><p align=\"center\"><span style=\" font-weight:696; text-decoration: underline;\">Licensing</span></p><p>If any of the below information is incorrect, please contact me and I will fix it.</p><p><span style=\" font-weight:696;\">Juiced Editor</span> is licensed under the <span style=\" font-weight:696;\">MIT License</span>.</p><p>MIT License</p><p>Copyright (c) 2022 N1GHTMAR3</p><p>Permission is hereby granted, free of charge, to any person obtaining a copy\u00a0of this software and associated documentation files (the &quot;Software&quot;), to deal\u00a0in the Software without restriction, including without limitation the rights\u00a0to use, copy, modify, merge, publish, distribute, sublicense, and/or sell\u00a0copies of the Software, and to permit persons to whom the Software is\u00a0furnished to do so, subject to the following conditions:</p><p>The above copyright notice and this permission notice shall be included in a"
                        "ll\u00a0copies or substantial portions of the Software.</p><p>THE SOFTWARE IS PROVIDED &quot;AS IS&quot;, WITHOUT WARRANTY OF ANY KIND, EXPRESS OR\u00a0IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,\u00a0FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE\u00a0AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER\u00a0LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,\u00a0OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE\u00a0SOFTWARE.</p><p><br/></p><p><a href=\"https://wiki.qt.io/Qt_for_Python\"><span style=\" font-weight:696; text-decoration: underline; color:#0000ff;\">PySide2</span></a> is licensed under the <span style=\" font-weight:696;\">GNU Lesser General Public License</span>, version 3.</p><p><span style=\" font-size:large; font-weight:696;\">GNU LESSER GENERAL PUBLIC LICENSE</span></p><p align=\"center\">Version 3, 29 June 2007 </p><p>Copyright \u00a9 2007 Free Software Founda"
                        "tion, Inc. &lt;<a href=\"https://fsf.org/\"><span style=\" text-decoration: underline; color:#0000ff;\">https://fsf.org/</span></a>&gt;</p><p>Everyone is permitted to copy and distribute verbatim copies of this license document, but changing it is not allowed. </p><p>This version of the GNU Lesser General Public License incorporates the terms and conditions of version 3 of the GNU General Public License, supplemented by the additional permissions listed below. </p><h4 style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><a name=\"section0\"/><span style=\" font-size:medium; font-weight:696;\">0</span><span style=\" font-size:medium; font-weight:696;\">. Additional Definitions.</span></h4><p>As used herein, \u201cthis License\u201d refers to version 3 of the GNU Lesser General Public License, and the \u201cGNU GPL\u201d refers to version 3 of the GNU General Public License. </p><p>\u201cThe Library\u201d refers to a covered work governed by this"
                        " License, other than an Application or a Combined Work as defined below. </p><p>An \u201cApplication\u201d is any work that makes use of an interface provided by the Library, but which is not otherwise based on the Library. Defining a subclass of a class defined by the Library is deemed a mode of using an interface provided by the Library. </p><p>A \u201cCombined Work\u201d is a work produced by combining or linking an Application with the Library. The particular version of the Library with which the Combined Work was made is also called the \u201cLinked Version\u201d. </p><p>The \u201cMinimal Corresponding Source\u201d for a Combined Work means the Corresponding Source for the Combined Work, excluding any source code for portions of the Combined Work that, considered in isolation, are based on the Application, and not on the Linked Version. </p><p>The \u201cCorresponding Application Code\u201d for a Combined Work means the object code and/or source code for the Application, including any data and utility prog"
                        "rams needed for reproducing the Combined Work from the Application, but excluding the System Libraries of the Combined Work. </p><h4 style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><a name=\"section1\"/><span style=\" font-size:medium; font-weight:696;\">1</span><span style=\" font-size:medium; font-weight:696;\">. Exception to Section 3 of the GNU GPL.</span></h4><p>You may convey a covered work under sections 3 and 4 of this License without being bound by section 3 of the GNU GPL. </p><h4 style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><a name=\"section2\"/><span style=\" font-size:medium; font-weight:696;\">2</span><span style=\" font-size:medium; font-weight:696;\">. Conveying Modified Versions.</span></h4><p>If you modify a copy of the Library, and, in your modifications, a facility refers to a function or data to be supplied by an Application that uses the facili"
                        "ty (other than as an argument passed when the facility is invoked), then you may convey a copy of the modified version: </p><ul style=\"margin-top: 0px; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; -qt-list-indent: 1;\"><li style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">a) under this License, provided that you make a good faith effort to ensure that, in the event an Application does not supply the function or data, the facility still operates, and performs whatever part of its purpose remains meaningful, or </li><li style=\" margin-top:0px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">b) under the GNU GPL, with none of the additional permissions of this License applicable to that copy. </li></ul><h4 style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><a name=\"section3\"/><span style=\" font-size:medium; font-wei"
                        "ght:696;\">3</span><span style=\" font-size:medium; font-weight:696;\">. Object Code Incorporating Material from Library Header Files.</span></h4><p>The object code form of an Application may incorporate material from a header file that is part of the Library. You may convey such object code under terms of your choice, provided that, if the incorporated material is not limited to numerical parameters, data structure layouts and accessors, or small macros, inline functions and templates (ten or fewer lines in length), you do both of the following: </p><ul style=\"margin-top: 0px; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; -qt-list-indent: 1;\"><li style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">a) Give prominent notice with each copy of the object code that the Library is used in it and that the Library and its use are covered by this License. </li><li style=\" margin-top:0px; margin-bottom:12px; margin-left:0px; margin-right:0"
                        "px; -qt-block-indent:0; text-indent:0px;\">b) Accompany the object code with a copy of the GNU GPL and this license document. </li></ul><h4 style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><a name=\"section4\"/><span style=\" font-size:medium; font-weight:696;\">4</span><span style=\" font-size:medium; font-weight:696;\">. Combined Works.</span></h4><p>You may convey a Combined Work under terms of your choice that, taken together, effectively do not restrict modification of the portions of the Library contained in the Combined Work and reverse engineering for debugging such modifications, if you also do each of the following: </p><ul style=\"margin-top: 0px; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; -qt-list-indent: 1;\"><li style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">a) Give prominent notice with each copy of the Combined Work that the Library is used"
                        " in it and that the Library and its use are covered by this License. </li><li style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">b) Accompany the Combined Work with a copy of the GNU GPL and this license document. </li><li style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">c) For a Combined Work that displays copyright notices during execution, include the copyright notice for the Library among these notices, as well as a reference directing the user to the copies of the GNU GPL and this license document. </li><li style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">d) Do one of the following: </li><ul style=\"margin-top: 0px; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; -qt-list-indent: 2;\"><li style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-inde"
                        "nt:0px;\">0) Convey the Minimal Corresponding Source under the terms of this License, and the Corresponding Application Code in a form suitable for, and under terms that permit, the user to recombine or relink the Application with a modified version of the Linked Version to produce a modified Combined Work, in the manner specified by section 6 of the GNU GPL for conveying Corresponding Source. </li><li style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">1) Use a suitable shared library mechanism for linking with the Library. A suitable mechanism is one that (a) uses at run time a copy of the Library already present on the user's computer system, and (b) will operate properly with a modified version of the Library that is interface-compatible with the Linked Version. </li></ul><li style=\" margin-top:0px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">e) Provide Installation Information, but only if "
                        "you would otherwise be required to provide such information under section 6 of the GNU GPL, and only to the extent that such information is necessary to install and execute a modified version of the Combined Work produced by recombining or relinking the Application with a modified version of the Linked Version. (If you use option 4d0, the Installation Information must accompany the Minimal Corresponding Source and Corresponding Application Code. If you use option 4d1, you must provide the Installation Information in the manner specified by section 6 of the GNU GPL for conveying Corresponding Source.) </li></ul><h4 style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><a name=\"section5\"/><span style=\" font-size:medium; font-weight:696;\">5</span><span style=\" font-size:medium; font-weight:696;\">. Combined Libraries.</span></h4><p>You may place library facilities that are a work based on the Library side by side in a single library together w"
                        "ith other library facilities that are not Applications and are not covered by this License, and convey such a combined library under terms of your choice, if you do both of the following: </p><ul style=\"margin-top: 0px; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; -qt-list-indent: 1;\"><li style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">a) Accompany the combined library with a copy of the same work based on the Library, uncombined with any other library facilities, conveyed under the terms of this License. </li><li style=\" margin-top:0px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">b) Give prominent notice with the combined library that part of it is a work based on the Library, and explaining where to find the accompanying uncombined form of the same work. </li></ul><h4 style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-in"
                        "dent:0px;\"><a name=\"section6\"/><span style=\" font-size:medium; font-weight:696;\">6</span><span style=\" font-size:medium; font-weight:696;\">. Revised Versions of the GNU Lesser General Public License.</span></h4><p>The Free Software Foundation may publish revised and/or new versions of the GNU Lesser General Public License from time to time. Such new versions will be similar in spirit to the present version, but may differ in detail to address new problems or concerns. </p><p>Each version is given a distinguishing version number. If the Library as you received it specifies that a certain numbered version of the GNU Lesser General Public License \u201cor any later version\u201d applies to it, you have the option of following the terms and conditions either of that published version or of any later version published by the Free Software Foundation. If the Library as you received it does not specify a version number of the GNU Lesser General Public License, you may choose any version of the GNU Lesser Gener"
                        "al Public License ever published by the Free Software Foundation. </p><p>If the Library as you received it specifies that a proxy can decide whether future versions of the GNU Lesser General Public License shall apply, that proxy's public statement of acceptance of any version is permanent authorization for you to choose that version for the Library. </p><p><br/></p><p><a href=\"https://pyinstaller.org/en/stable/\"><span style=\" font-weight:696; text-decoration: underline; color:#0000ff;\">PyInstaller</span></a> is licensed under the <span style=\" font-weight:696;\">GNU General Public License</span>, version 2. Juiced Editor falls under the following Bootloader Exception:</p><p>Bootloader Exception<br/>--------------------<br/>In addition to the permissions in the GNU General Public License, the<br/>authors give you unlimited permission to link or embed compiled bootloader<br/>and related files into combinations with other programs, and to distribute<br/>those combinations without any restriction coming from"
                        " the use of those<br/>files. (The General Public License restrictions do apply in other respects;<br/>for example, they cover modification of the files, and distribution when<br/>not linked into a combined executable.)</p><p><br/></p><p><a href=\"https://github.com/brentvollebregt/auto-py-to-exe\"><span style=\" font-weight:696; text-decoration: underline; color:#0000ff;\">Auto PY to EXE</span></a> is licensed under the <span style=\" font-weight:696;\">MIT License</span>.</p><p>MIT License</p><p>Copyright (c) 2018 Brent Vollebregt</p><p>Permission is hereby granted, free of charge, to any person obtaining a copy\u00a0of this software and associated documentation files (the &quot;Software&quot;), to deal\u00a0in the Software without restriction, including without limitation the rights\u00a0to use, copy, modify, merge, publish, distribute, sublicense, and/or sell\u00a0copies of the Software, and to permit persons to whom the Software is\u00a0furnished to do so, subject to the following conditions:</p><p>The abo"
                        "ve copyright notice and this permission notice shall be included in all\u00a0copies or substantial portions of the Software.</p><p>THE SOFTWARE IS PROVIDED &quot;AS IS&quot;, WITHOUT WARRANTY OF ANY KIND, EXPRESS OR\u00a0IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,\u00a0FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE\u00a0AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER\u00a0LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,\u00a0OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE\u00a0SOFTWARE.</p></body></html>", None))
    # retranslateUi

