# Form implementation generated from reading ui file 'JEMain.ui'
#
# Created by: PyQt6 UI code generator 6.3.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_JEMainWindow(object):
    def setupUi(self, JEMainWindow):
        JEMainWindow.setObjectName("JEMainWindow")
        JEMainWindow.resize(370, 140)
        JEMainWindow.setMinimumSize(QtCore.QSize(250, 140))
        JEMainWindow.setMaximumSize(QtCore.QSize(370, 140))
        self.centralwidget = QtWidgets.QWidget(JEMainWindow)
        self.centralwidget.setEnabled(True)
        self.centralwidget.setObjectName("centralwidget")
        self.InfoHeader = QtWidgets.QLabel(self.centralwidget)
        self.InfoHeader.setGeometry(QtCore.QRect(10, 10, 50, 20))
        self.InfoHeader.setObjectName("InfoHeader")
        self.InfoExeType = QtWidgets.QLabel(self.centralwidget)
        self.InfoExeType.setGeometry(QtCore.QRect(120, 30, 240, 20))
        self.InfoExeType.setObjectName("InfoExeType")
        self.InfoExePath = QtWidgets.QLabel(self.centralwidget)
        self.InfoExePath.setGeometry(QtCore.QRect(120, 50, 240, 20))
        self.InfoExePath.setText("")
        self.InfoExePath.setObjectName("InfoExePath")
        self.InfoExeSize = QtWidgets.QLabel(self.centralwidget)
        self.InfoExeSize.setGeometry(QtCore.QRect(120, 70, 240, 20))
        self.InfoExeSize.setText("")
        self.InfoExeSize.setObjectName("InfoExeSize")
        self.InfoDecrypt = QtWidgets.QLabel(self.centralwidget)
        self.InfoDecrypt.setGeometry(QtCore.QRect(10, 30, 60, 20))
        self.InfoDecrypt.setObjectName("InfoDecrypt")
        self.InfoDecryptStatus = QtWidgets.QLabel(self.centralwidget)
        self.InfoDecryptStatus.setGeometry(QtCore.QRect(80, 30, 20, 20))
        self.InfoDecryptStatus.setText("")
        self.InfoDecryptStatus.setObjectName("InfoDecryptStatus")
        JEMainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(JEMainWindow)
        self.menubar.setEnabled(True)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 370, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        JEMainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(JEMainWindow)
        self.statusbar.setEnabled(False)
        self.statusbar.setSizeGripEnabled(False)
        self.statusbar.setObjectName("statusbar")
        JEMainWindow.setStatusBar(self.statusbar)
        self.actionOpen = QtGui.QAction(JEMainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.menuFile.addAction(self.actionOpen)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(JEMainWindow)
        QtCore.QMetaObject.connectSlotsByName(JEMainWindow)

    def retranslateUi(self, JEMainWindow):
        _translate = QtCore.QCoreApplication.translate
        JEMainWindow.setWindowTitle(_translate("JEMainWindow", "Juiced Editor"))
        self.InfoHeader.setText(_translate("JEMainWindow", "<html><head/><body><p><span style=\" font-weight:700;\">Info</span></p></body></html>"))
        self.InfoExeType.setText(_translate("JEMainWindow", "No .exe loaded"))
        self.InfoDecrypt.setText(_translate("JEMainWindow", "Decrypted:"))
        self.menuFile.setTitle(_translate("JEMainWindow", "File"))
        self.actionOpen.setText(_translate("JEMainWindow", "Open..."))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    JEMainWindow = QtWidgets.QMainWindow()
    ui = Ui_JEMainWindow()
    ui.setupUi(JEMainWindow)
    JEMainWindow.show()
    sys.exit(app.exec())
