# Form implementation generated from reading ui file 'JEMain.ui'
#
# Created by: PyQt6 UI code generator 6.3.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_JEMainWindow(object):
    def setupUi(self, JEMainWindow):
        JEMainWindow.setObjectName("JEMainWindow")
        JEMainWindow.resize(500, 140)
        JEMainWindow.setMinimumSize(QtCore.QSize(500, 140))
        JEMainWindow.setMaximumSize(QtCore.QSize(500, 140))
        self.centralwidget = QtWidgets.QWidget(JEMainWindow)
        self.centralwidget.setEnabled(True)
        self.centralwidget.setObjectName("centralwidget")
        self.InfoHeader = QtWidgets.QLabel(self.centralwidget)
        self.InfoHeader.setGeometry(QtCore.QRect(10, 10, 50, 20))
        self.InfoHeader.setObjectName("InfoHeader")
        self.InfoExeType = QtWidgets.QLabel(self.centralwidget)
        self.InfoExeType.setGeometry(QtCore.QRect(10, 30, 240, 20))
        self.InfoExeType.setObjectName("InfoExeType")
        self.InfoExeSize = QtWidgets.QLabel(self.centralwidget)
        self.InfoExeSize.setGeometry(QtCore.QRect(10, 70, 240, 20))
        self.InfoExeSize.setObjectName("InfoExeSize")
        self.InfoDecrypt = QtWidgets.QLabel(self.centralwidget)
        self.InfoDecrypt.setGeometry(QtCore.QRect(270, 30, 60, 20))
        self.InfoDecrypt.setObjectName("InfoDecrypt")
        self.InfoDecryptStatus = QtWidgets.QLabel(self.centralwidget)
        self.InfoDecryptStatus.setGeometry(QtCore.QRect(370, 30, 20, 20))
        self.InfoDecryptStatus.setStyleSheet("color: blue;")
        self.InfoDecryptStatus.setObjectName("InfoDecryptStatus")
        self.InfoServerPatch = QtWidgets.QLabel(self.centralwidget)
        self.InfoServerPatch.setGeometry(QtCore.QRect(270, 50, 90, 20))
        self.InfoServerPatch.setObjectName("InfoServerPatch")
        self.InfoServerPatchStatus = QtWidgets.QLabel(self.centralwidget)
        self.InfoServerPatchStatus.setGeometry(QtCore.QRect(370, 50, 20, 20))
        self.InfoServerPatchStatus.setStyleSheet("color: red;")
        self.InfoServerPatchStatus.setObjectName("InfoServerPatchStatus")
        self.InfoServerPatchButton = QtWidgets.QPushButton(self.centralwidget)
        self.InfoServerPatchButton.setEnabled(False)
        self.InfoServerPatchButton.setGeometry(QtCore.QRect(400, 50, 90, 20))
        self.InfoServerPatchButton.setObjectName("InfoServerPatchButton")
        self.InfoExePath = QtWidgets.QLineEdit(self.centralwidget)
        self.InfoExePath.setEnabled(True)
        self.InfoExePath.setGeometry(QtCore.QRect(10, 50, 240, 20))
        self.InfoExePath.setReadOnly(True)
        self.InfoExePath.setObjectName("InfoExePath")
        JEMainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(JEMainWindow)
        self.menubar.setEnabled(True)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 500, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        JEMainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(JEMainWindow)
        self.statusbar.setEnabled(False)
        self.statusbar.setSizeGripEnabled(False)
        self.statusbar.setObjectName("statusbar")
        JEMainWindow.setStatusBar(self.statusbar)
        self.actionOpen = QtGui.QAction(JEMainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave = QtGui.QAction(JEMainWindow)
        self.actionSave.setEnabled(False)
        self.actionSave.setObjectName("actionSave")
        self.actionSaveAs = QtGui.QAction(JEMainWindow)
        self.actionSaveAs.setEnabled(False)
        self.actionSaveAs.setObjectName("actionSaveAs")
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionSaveAs)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(JEMainWindow)
        QtCore.QMetaObject.connectSlotsByName(JEMainWindow)

    def retranslateUi(self, JEMainWindow):
        _translate = QtCore.QCoreApplication.translate
        JEMainWindow.setWindowTitle(_translate("JEMainWindow", "Juiced Editor"))
        self.InfoHeader.setText(_translate("JEMainWindow", "<html><head/><body><p><span style=\" font-weight:700;\">Info</span></p></body></html>"))
        self.InfoExeType.setText(_translate("JEMainWindow", "Juiced.exe (unpatched)"))
        self.InfoExeSize.setText(_translate("JEMainWindow", "12,560,384 bytes"))
        self.InfoDecrypt.setText(_translate("JEMainWindow", "Decrypted:"))
        self.InfoDecryptStatus.setText(_translate("JEMainWindow", "Yes"))
        self.InfoServerPatch.setText(_translate("JEMainWindow", "Servers patched:"))
        self.InfoServerPatchStatus.setText(_translate("JEMainWindow", "No"))
        self.InfoServerPatchButton.setText(_translate("JEMainWindow", "Patch Servers"))
        self.InfoExePath.setText(_translate("JEMainWindow", "C:\\\\Program Files (x86)\\\\THQ\\\\Juiced"))
        self.menuFile.setTitle(_translate("JEMainWindow", "File"))
        self.actionOpen.setText(_translate("JEMainWindow", "Open..."))
        self.actionSave.setText(_translate("JEMainWindow", "Save"))
        self.actionSaveAs.setText(_translate("JEMainWindow", "Save As..."))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    JEMainWindow = QtWidgets.QMainWindow()
    ui = Ui_JEMainWindow()
    ui.setupUi(JEMainWindow)
    JEMainWindow.show()
    sys.exit(app.exec())
